######################################################################
# Automatically generated by qmake (2.01a) ? 9? 26 00:36:36 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ../filedlg.h ../command.h ../precomp.h
SOURCES += filedlg.cpp
